---
- name: install waybar package
  include_role:
    name: installAurPackages
- name: Create waybar config directory
  file:
    path: ~/.config/waybar
    state: directory
- name: place config file
  copy:
    src: files/config
    dest: ~/.config/waybar/config
- name: place style file
  copy:
    src: files/style.css
    dest: ~/.config/waybar/style.css
- name: create scripts directory
  file:
    path: ~/.config/waybar/scripts
    state: directory
- name: place scripts
  copy:
    src: files/scripts/
    dest: ~/.config/waybar/scripts/
    mode: a+x
