---
- name: Create nwgdrawer config directory
  file:
    path: ~/.config/nwg-drawer
    state: directory
- name: config
  copy:
    src: files/drawer.css
    dest: ~/.config/nwg-drawer/drawer.css

- name: install nwg-drawer
  include_role:
    name: installAurPackages
