---
- name: install nvim package arch
  pacman:
    name: neovim
    state: present
  when: 
  - ansible_facts['distribution'] == "ArchLInux"
- name: install nvim package 
  yum:
    name: neovim
    state: present
    when:
    - ansible_facts['distribution'] == "RedHat"
    become: yes
    become_method: sudo
    become_user: root
- name: clone nvchad repo
  git:
    repo: https://github.com/NvChad/NvChad
    dest: ~/.config/nvim
    clone: yes
    update: yes
    depth: 1
- name: create custom directory
  file:
    path: ~/.config/nvim/lua/custom
    state: directory
- name: place custom files
  copy:
    src: files/custom/
    dest: ~/.config/nvim/lua/custom/
