---
- name: install nvim package arch
  pacman:
    name: neovim
    state: present
  when: 
  - ansible_facts['distribution'] == "ArchLInux"
- name: install nvim package 
  yum:
    name: neovim
    state: present
  when:
  - ansible_facts['distribution'] == "RedHat"
- name: clone nvchad repo
  git:
    repo: https://github.com/NvChad/NvChad
    dest: ~/.config/nvim
    clone: yes
    update: yes
    depth: 1
- block:
  - name: check if directory exists
    stat:
      path: '~/.config/nvim/lua/custom'
    register: directory_data
  - debug: var=directory_data.path
  - name: create custom directory
    copy:
      src: files/custom/
      dest: ~/config/nvim/lua/custom/
    when: not directory_data.stat.exists 
